version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "pointcollect"
    ports:
      - "5432:5432"
    volumes:
      - /home/docker/containers/PostgreSQL:/var/lib/postgresql/data 
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pointcollect@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge